const DEFAULT_VALUE = 1000;

export enum AccessControlTransactions {
  RESOURCE = DEFAULT_VALUE,
  CREATE = DEFAULT_VALUE,
  UPDATE = DEFAULT_VALUE,
  DELETE = DEFAULT_VALUE,
  READ = DEFAULT_VALUE,
}
