const DASHBOARD_RESOURCE = 200;

export enum DashboardTransactions {
  RESOURCE = DASHBOARD_RESOURCE,
  CREATE = DASHBOARD_RESOURCE,
  UPDATE = DASHBOARD_RESOURCE,
  DELETE = DASHBOARD_RESOURCE,
  READ = DASHBOARD_RESOURCE,
}
